### ISSUE TITLE
unable to compile coverletter

### ISSUE THREAD

**Issue by DragonHunter274** [arubertoson/latex-resume#2]
No matter what I try, compiling the cover letter results in 
```
! Missing number, treated as zero.
<to be read again> 
                   \protect 
l.65 ^^I^^I^^I\begin
                    {flushleft} 
```

I can get the resume to compile  by renaming textfont in resume.cls and entities.sty and changing the Ubuntu font to the correct name but I just can't figure out whats wrong with the cover letter

I tried using the current texlive version and the 2018 version, I couldnt get MiKtex running

**Comment by arubertoson** [comment]
It's been forever since I touched any of this, I can't say I would know where to begin, and unfortunately don't have the time to have a proper look... Sorry.
